export type ProfessionalInput = {
    theme: "announcement" | "promotion" | "invite" | "relation";
    business: string;
    address: string;
    website: string;
    customer: string;
    item?: string;
    topic?: string;
    start?: string;
    end?: string;
    datetime?: string;
    speakers?: string;
    agenda?: string;
    location?: string;
    message: string;
    disclaimers?: string;
    unsub: string;
    color: string;
    logo: string;
    picture?: string;
    text?: string;
    cta?: string;
    code?: string;
};